# Generated by Django 3.2 on 2024-06-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Categorirs',
            new_name='categories',
        ),
    ]
